version: '3.5'
services:
    frontend:
        container_name: frontend
        build:
          context: .
          dockerfile: frontend/Dockerfile
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - '3000:3000'
    
    db:
        container_name: db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: suas
            POSTGRES_PASSWORD: suas123
        ports:
            - 5432:5432
        volumes:
            - ./database/docker-data/postgres:/var/lib/postgresql/data
            - ./database:/docker-entrypoint-initdb.d

    
    api-symfony:
        container_name: api-symfony
        build: ./backend/symfony
        restart: on-failure
        environment:
            - APP_ENV=local
        volumes:
            - ./backend/symfony:/app
        depends_on:
            - db
        links:
            - db

    nginx:
        container_name: nginx
        image: nginx:1.17.8
        restart: unless-stopped
        depends_on:
            - api-symfony
        ports:
            - 8000:80
        volumes:
            - ./backend/symfony:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - api-symfony



