<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZoXji1U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZoXji1U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZoXji1U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZoXji1U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZoXji1U\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZoXji1U',
    'container.build_id' => '5a589df8',
    'container.build_time' => 1646024920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZoXji1U');
