controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


api:
    path: /test
    controller: App\Controller\TestController::test